export const tabelaPrecosList = [
  {
    aparelho: "Ar condicionado",
    potencia: 1200,
    unidade: "hora",
    consumo: 1.2,
    custo: 0.96,
  },
  {
    aparelho: "Cafeteira",
    potencia: 500,
    unidade: "hora",
    consumo: 0.5,
    custo: 0.4,
  },
  {
    aparelho: "Chuveiro",
    potencia: 4800,
    unidade: "minuto",
    consumo: 0.08,
    custo: 0.06,
  },
  {
    aparelho: "Ferro elétrico",
    potencia: 1000,
    unidade: "hora",
    consumo: 1,
    custo: 0.8,
  },
  {
    aparelho: "Forno de microondas",
    potencia: 1400,
    unidade: "hora",
    consumo: 1.4,
    custo: 1.12,
  },
  {
    aparelho: "Forno elétrico",
    potencia: 600,
    unidade: "hora",
    consumo: 0.6,
    custo: 0.48,
  },
  {
    aparelho: "Lâmpada de LED",
    potencia: 8,
    unidade: "hora",
    consumo: 0.01,
    custo: 0.006,
  },
  {
    aparelho: "Lâmpada fluorescente",
    potencia: 15,
    unidade: "hora",
    consumo: 0.02,
    custo: 0.012,
  },
  {
    aparelho: "Lâmpada incandescente",
    potencia: 60,
    unidade: "hora",
    consumo: 0.06,
    custo: 0.05,
  },
  {
    aparelho: "Notebook",
    potencia: 90,
    unidade: "hora",
    consumo: 0.09,
    custo: 0.07,
  },
  {
    aparelho: "Sanduicheira",
    potencia: 1000,
    unidade: "hora",
    consumo: 1,
    custo: 0.8,
  },
  {
    aparelho: "Secador de cabelos",
    potencia: 1200,
    unidade: "hora",
    consumo: 1.2,
    custo: 0.96,
  },
  {
    aparelho: "TV",
    potencia: 120,
    unidade: "hora",
    consumo: 0.12,
    custo: 0.1,
  },
];
